### PR TITLE
Optimising get cookie value function

### PR DESCRIPTION
**Pull request by davidnormo**
We were finding that the evaluation time of the OpenTag script was spending a lot of time in the cookie get function alone.
screen shot 2018-10-24 at 13 19 21
This PR introduces an optimised cookie get function.

### CODE REVIEW

**Comment by peterfronc** [comment]
Thanks for the commit, i will have a look into it.

**Comment by peterfronc** [comment]
I have done some quick tests and as expected regex solution is actually much slower (regex always is).

The screen below shows it:
screen shot 2018-10-24 at 13 55 50

Have you tried improving the loop? Its based on the mathematical minimum but some shortcuts are possible I think (caching for example).

As this function is extensively used I will look for some extra improvements (although 50ms< values in total are pretty low).

**Comment by davidnormo** [comment]
Ah. Ok thanks for testing! I think we found somewhere that suggested the regex version was faster but apparently not.

We were seeing cases that `Cookie.get` was taking much longer, I think on lower powered devices:
screen shot 2018-10-01 at 12 21 17 1

Yeah it seems like it's worth investigating a bit more, will try and spend some time on this.

**Comment by peterfronc** [comment]
Not a problem, I'm the architect of the system. The cookie reading has only one really heavy section, it is accessing the cookie itself. Have a try in console following code:
`
var st = Date.now();for (var i=0;i < 1000; i++) {document.cookie === "equal"} ;console.log(Date.now() - st)
`
You will see its same as the getter.

We do read the cookie whenever necessary and it's depending on tags that use it, there is always some room for tiny performance tweaks but it is not gonna save much as I think the problem is not in the Opentag but structure of scripts being used on the site and what those script do. How injection is implemented by particular tags is pretty much outside of Opentag control. 
If you need more assistance just use my email at Qubit and you can contact me directly (if you provide more details on environment it will be great too).

I would advise on checking if all tags needs to fire immediately, it will allow to distribute processing to times when its not causing any issues. Dependency chain of async triggers may be good idea.

**Comment by peterfronc** [comment]
Im gonna look into limiting the reads in general too.

**Comment by peterfronc** [comment]
@davidnormo can you also paste the breakdown for the `k.get` function? I have prepared patch that should fix the issue (it on mirrored repository).

**Comment by peterfronc** [comment]
@davidnormo I have released updates today in Opentag, I am confident the updates will resolve the cookie access issues. Let me know if there is anything else I can help you with.

**Comment by peterfronc** [comment]
Btw. You will need to redeploy the container in your Opentag account (click edit, save and publish).

**Pull request closed without merging**
